/**
 * TypeScript declarations to add __auditUserId to Prisma operation arguments
 *
 * This allows type-safe audit logging without "as any" type casts.
 * __auditUserId is REQUIRED for all operations - use context.user.id.
 *
 * AUTO-GENERATED by scripts/generate-audit-types.js
 * DO NOT EDIT MANUALLY - run: node scripts/generate-audit-types.js
 */

import { Prisma } from '@prisma/client';

declare module '@prisma/client' {
  // User operations
  interface UserCreateArgs {
    __auditUserId: number;
  }
  interface UserUpdateArgs {
    __auditUserId: number;
  }
  interface UserUpsertArgs {
    __auditUserId: number;
  }

  // Patient operations
  interface PatientCreateArgs {
    __auditUserId: number;
  }
  interface PatientUpdateArgs {
    __auditUserId: number;
  }
  interface PatientUpsertArgs {
    __auditUserId: number;
  }

  // ConsultationRequest operations
  interface ConsultationRequestCreateArgs {
    __auditUserId: number;
  }
  interface ConsultationRequestUpdateArgs {
    __auditUserId: number;
  }
  interface ConsultationRequestUpsertArgs {
    __auditUserId: number;
  }

  // Slot operations
  interface SlotCreateArgs {
    __auditUserId: number;
  }
  interface SlotUpdateArgs {
    __auditUserId: number;
  }
  interface SlotUpsertArgs {
    __auditUserId: number;
  }

  // Consultation operations
  interface ConsultationCreateArgs {
    __auditUserId: number;
  }
  interface ConsultationUpdateArgs {
    __auditUserId: number;
  }
  interface ConsultationUpsertArgs {
    __auditUserId: number;
  }

  // ConsultationCall operations
  interface ConsultationCallCreateArgs {
    __auditUserId: number;
  }
  interface ConsultationCallUpdateArgs {
    __auditUserId: number;
  }
  interface ConsultationCallUpsertArgs {
    __auditUserId: number;
  }

  // Config operations
  interface ConfigCreateArgs {
    __auditUserId: number;
  }
  interface ConfigUpdateArgs {
    __auditUserId: number;
  }
  interface ConfigUpsertArgs {
    __auditUserId: number;
  }

  // SmsMessage operations
  interface SmsMessageCreateArgs {
    __auditUserId: number;
  }
  interface SmsMessageUpdateArgs {
    __auditUserId: number;
  }
  interface SmsMessageUpsertArgs {
    __auditUserId: number;
  }

  // OutgoingSmsMessage operations
  interface OutgoingSmsMessageCreateArgs {
    __auditUserId: number;
  }
  interface OutgoingSmsMessageUpdateArgs {
    __auditUserId: number;
  }
  interface OutgoingSmsMessageUpsertArgs {
    __auditUserId: number;
  }

  // AuditEvent operations
  interface AuditEventCreateArgs {
    __auditUserId: number;
  }
  interface AuditEventUpdateArgs {
    __auditUserId: number;
  }
  interface AuditEventUpsertArgs {
    __auditUserId: number;
  }
}
